### PR TITLE
v18.0

### PR DESCRIPTION
**Pull request by qq7**

### CODE REVIEW

**Review by OnGle — APPROVED** [review]
lgtm

Fwiw screenshots are now done via clicksnap (https://github.com/turnkeylinux/clicksnap), if you don't know rust I'm happy to handle that though.

**Comment by JedMeister** [comment]
FWIW, Zhenya has already done that (see https://github.com/turnkeylinux/clicksnap/pull/17 - although I haven't tested myself). I'm guessing that he just uploaded the screenshots that he generated (via clicksnap).

**Comment by OnGle** [comment]
Oh my bad he has too :sweat_smile:

**Review by Christie018 — APPROVED** [review]
I've reviewed and approved the code changes.

**Pull request merged**
